// AUTO-GENERATED by gen-pool.mjs — do not edit by hand.
export default [
  {
    "id": "4fuar55aCMZgvxMZM1sboXcCwr6jLMuANwNtC69sbCzx",
    "teams": [
      "Argentina",
      "Cape Verde"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/QBJHQ3O1IdxCq1LAJqWlyMZisWVOrFXP-8BMgrrkxsE",
    "match": "Argentina vs Cape Verde",
    "score": "1–0",
    "assetExplorer": "https://explorer.solana.com/address/4fuar55aCMZgvxMZM1sboXcCwr6jLMuANwNtC69sbCzx?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3jdjouck3uf3rnE1ktcYa4BwminXVF62in959xqcxpfKyNYMDuamhdGpTPpb5bz79zfmSvZRw3pQTfJAwnKwXPBZ?cluster=devnet",
    "live": false
  },
  {
    "id": "qdmsBUhmf6yL8PEfmsmEAVHCU5mw9RETAd4Wvp8oWtW",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/JAfy9rYDd_b6tIZ3w9ytf50syfzqEwKuQLMjroHCpdc",
    "match": "Brazil vs Norway",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/qdmsBUhmf6yL8PEfmsmEAVHCU5mw9RETAd4Wvp8oWtW?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/XtjcnYiFf2qyP9E7UEL527icpa3L2QRJm2cFsVrqKDBA15nn3fTjaAKL1QpQZVx2q58YxUxPEbWWrL7muCSzGW2?cluster=devnet",
    "live": false
  },
  {
    "id": "8rqd4KjugeQsjzakEM7wTSLT2Vuip7rjAoYxkGuVtPKZ",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/sTA3BFBZ37GzhRmzJrKglsdgTqb5W3muYRq6T_c8nsk",
    "match": "Brazil vs Norway",
    "score": "0–0",
    "assetExplorer": "https://explorer.solana.com/address/8rqd4KjugeQsjzakEM7wTSLT2Vuip7rjAoYxkGuVtPKZ?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2khGhrT9FdvTe9DN3FERRL4EJEhT84L8A5bHTqE47y5gEnFPEnBR3UVEac4WMU4AhB1QfVgcophswJonw8yhkFh7?cluster=devnet",
    "live": false
  },
  {
    "id": "2rHiPEuVqTyKz4nRtEWBznQum7mthQCXAxsAtKax87MF",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/mg5P5w6mjnVNMYc15FWKEKUYVyk9MuaMGahPXmUKD3I",
    "match": "Brazil vs Norway",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/2rHiPEuVqTyKz4nRtEWBznQum7mthQCXAxsAtKax87MF?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2K68D78EAYg8WAbbDatFYTHXiaEfUR58HAZTrTy11tqmA31mNKkD2SzVAMBFHRQkwwbQGsMNcSuf9HK2TcpiN7Q7?cluster=devnet",
    "live": false
  },
  {
    "id": "ExXsQfwSio7v9mn2Bw9BfftBVWFLBMNkduicbGvDvsBW",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/e_TB0oIZyeJgQ6HdI9QK8iBbRIbGdBHQE8cDk1ObkNE",
    "match": "Brazil vs Norway",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/ExXsQfwSio7v9mn2Bw9BfftBVWFLBMNkduicbGvDvsBW?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2F1goozAE4NW7eUM1EcJAQFn9Z25CLj1MxRXcxJ1UfjNqG97gmywNcQ2VaWz3eb4tjcKyFHrYYgWq3atWqYy2dLV?cluster=devnet",
    "live": false
  },
  {
    "id": "CDtHAELeWAwrs5qukZWjt3umDuJ9zEqXF6oQuDtGCRD8",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/5oMXGFBQjiIw2jpwG2mrW4hWoCrHhZL8RB_mDSfRpN4",
    "match": "Brazil vs Norway",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/CDtHAELeWAwrs5qukZWjt3umDuJ9zEqXF6oQuDtGCRD8?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/auvpfUwtQ9e1HGoi8EPqGMAXq9E6WFnR5LZnN1mi7uAz6wvyyRuyMQZVy1zwPKMr5nTj4KjZqvXpNjKKdA5tMBc?cluster=devnet",
    "live": false
  },
  {
    "id": "HUVVDAo7ziBMzfJGooMdb8wkk2ZwTE4WbKSwqqYHPzP7",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/p6CUEoKLvCLfEmRHwCOA-RbnSqRaJg5SFnR9FotYbPw",
    "match": "Mexico vs England",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/HUVVDAo7ziBMzfJGooMdb8wkk2ZwTE4WbKSwqqYHPzP7?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/ukWpqyJT1PEw6SCb2qrp2ey9vJbWL5Qyu3P23A8V5MmQdYAcNWtmTptMnitPVvGrKbpK15fVRVQvv3e3wMNoi8g?cluster=devnet",
    "live": false
  },
  {
    "id": "B3dVq2ZtXfhk2phPFvoYQwbTGDUTFuwFCeZWMNfeqWwu",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/jPVY-ARXYlW3-TJyDh0rMaZv960t78v-CgsSb9A9SXk",
    "match": "Mexico vs England",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/B3dVq2ZtXfhk2phPFvoYQwbTGDUTFuwFCeZWMNfeqWwu?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2MPMVwR8UYNq5xjy12WXCwjtFMoZZ71o1EhMXuwfVdK1TGWYkLzKdcZ8nqwuQDCf6Cu9nviaWjssRQvBwqMmZnoC?cluster=devnet",
    "live": false
  },
  {
    "id": "huz4VgEb7cEqwJ8bf9E2er4eZ78BLP2r2MUXmfKfwzL",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/5m3flLeSd9lJ7XCkqAS3vFK6Ocd8mVzHbiPLNhANFkI",
    "match": "Mexico vs England",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/huz4VgEb7cEqwJ8bf9E2er4eZ78BLP2r2MUXmfKfwzL?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/Z2dKF2jhACpBaK8MCmPgzBh2FRLGW1D5yLUFmveAM4cRJxdYkNmPJ2EFkPAS85GnYMv3HGGzbQQFj5gmKEvq1on?cluster=devnet",
    "live": false
  },
  {
    "id": "BzNyknVxYGR68yxvXQTTRvw4twzyqM498AedhwwMN5CN",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "RED CARD",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/b8ZbZJGj8-Lr5hWBWSfNqAOIC2X3mPpl2_YofQlF6bA",
    "match": "Mexico vs England",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/BzNyknVxYGR68yxvXQTTRvw4twzyqM498AedhwwMN5CN?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/dLb9TDFcGwpzervm4BhnQmJ1Ru8y97Z9fiJpSMrJNB6qkFLR6vaWrywzprfa9GxYe6rdazF6e8mszVijtB21Ecq?cluster=devnet",
    "live": false
  },
  {
    "id": "75vXJPgsRfTip6CiDRWBgL2iKtL2VXQ5NnZKrVvgYVxY",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/5HMuQdKhOqRw4CsRToEhf4vjOwg1YPDnItf2Z9_HMbo",
    "match": "Mexico vs England",
    "score": "1–3",
    "assetExplorer": "https://explorer.solana.com/address/75vXJPgsRfTip6CiDRWBgL2iKtL2VXQ5NnZKrVvgYVxY?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5oWvt4zarYnaihRdwBfdPF93evJKQu2hA7tMQ73ugsize2tUs8juju5k6a4iqAVu1cWVC9jWr72AE5T8dMrpdsyT?cluster=devnet",
    "live": false
  },
  {
    "id": "F6LFJ2kESD2rQGRipe3vQVwsmC6SvEUDyuFjjkYQ1jXB",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/HuDeTyZGnDLfDmxo9OROJ3P31FEdq360gTIN0bIPZAA",
    "match": "Mexico vs England",
    "score": "2–3",
    "assetExplorer": "https://explorer.solana.com/address/F6LFJ2kESD2rQGRipe3vQVwsmC6SvEUDyuFjjkYQ1jXB?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5pRaGgSKvc4MiSpJ7rn1jT6QoMXCHv9pY14q1NQ8X9CdrFoNEK3t8SykW5mVeFRrQxBh4vrUWqc58xwKpeeqFJVw?cluster=devnet",
    "live": false
  },
  {
    "id": "Cv2bqwj15wRZsVb9yoyjRkK8TXcStoWMzmxF8Au8fEyS",
    "teams": [
      "Portugal",
      "Spain"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/hSr3u67qrDeNVJVhtMxYaDJQ6_lP30wIXMJdOeujHaU",
    "match": "Portugal vs Spain",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/Cv2bqwj15wRZsVb9yoyjRkK8TXcStoWMzmxF8Au8fEyS?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5wEZzKtnoEcXhxNUxLvJvLpLkV7vEhWzwGuyrSTAo4jaNs2WFh8CTdy7LkRMd3nCcZJv7ZSgsSsjMMacz4HAW6Xw?cluster=devnet",
    "live": true
  },
  {
    "id": "FXBsRTFgYa57wDcdoGjmQisABm3YFEsez55KqE2kERFN",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/d0-i5z09gi_4xuE4ZX0oiRPOa-AnA1NhgQ0hk_g2MgU",
    "match": "USA vs Belgium",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/FXBsRTFgYa57wDcdoGjmQisABm3YFEsez55KqE2kERFN?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/kLnvYDy9qBRJaVaJZFyFzqvvJ9Czj86rthRf8rgHNPiKqKVLs2pdk9UbfHWj24qDPFXv7RpAT9Yg9kg3A2JCceL?cluster=devnet",
    "live": true
  },
  {
    "id": "DexpoT2emg9sMPErKmEYz8UDHmvH4BzCnqwTgBuqEsLB",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/HgLgCaeBoGJl1nDVBASVExFun9Qz4dlrLSI9PXaB74k",
    "match": "USA vs Belgium",
    "score": "1–1",
    "assetExplorer": "https://explorer.solana.com/address/DexpoT2emg9sMPErKmEYz8UDHmvH4BzCnqwTgBuqEsLB?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/31tL87UYcovjQ1e7nqcRt3ByTQZmHk6PCG6G4u69PNGpsifCGY6hFuSjNf3BAyhzNVfbK6vsbHTQSQcYQZeKk22q?cluster=devnet",
    "live": true
  },
  {
    "id": "9BnSVxPE8wdYhAzhkj2prz7rgtZHbUiv7G4p6tATwsTo",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/JgaQjEIPlUzZhxvE6cTG5kS83yyb0V7YAo3SWE-L2ro",
    "match": "USA vs Belgium",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/9BnSVxPE8wdYhAzhkj2prz7rgtZHbUiv7G4p6tATwsTo?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3pyjN98ax34zRJAUmZ2NzqV6bRHminARPZB9Mmf3BktrKVhpgPv5SF4uNaQ33YmFnaBYj2Zmy6o4QbKKtuqnDHt4?cluster=devnet",
    "live": true
  },
  {
    "id": "Gwn1UL8LuaxxqLYFd3PUVpx2e7gwmxVNxYwxkWeAjLPo",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/GzbDpcB6HovQ0BOYyH3SLqGCBTzV2yiVYZ3OlSXpwU0",
    "match": "USA vs Belgium",
    "score": "1–3",
    "assetExplorer": "https://explorer.solana.com/address/Gwn1UL8LuaxxqLYFd3PUVpx2e7gwmxVNxYwxkWeAjLPo?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/43TqCueDzkTBiFgETMvtoagHhpUqq2N3ekR2WQwrcy5i6UyMBL69TZ3tC893dr6RomStrsua612YtY9xu1rtXMMm?cluster=devnet",
    "live": true
  },
  {
    "id": "5AxNeSbTrGGdr6wtStsH9bpp2H6d1hVPePhWWcUVSg7y",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/ZjbsQTrHxB87k6K8UFQ0baND6fIFNJ6o2so6MMoaB8c",
    "match": "USA vs Belgium",
    "score": "1–4",
    "assetExplorer": "https://explorer.solana.com/address/5AxNeSbTrGGdr6wtStsH9bpp2H6d1hVPePhWWcUVSg7y?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4EkeD3nLj8oXkaUtQcuA2Hhud2eaCbnYuqGh8TwqKCWhc1hb4fzxvY7zX9TCkDZrxjJiDYSAbs67h9HhdPJp9mxS?cluster=devnet",
    "live": true
  },
  {
    "id": "Eie98xmcqZoamSjVEyooSpxCQ273fPaSp5P4WKsBJ1H6",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/dV-iWfLKU75n7QO8ydTrHCS36ePvQV3XyY4LgS9G84Q",
    "match": "Argentina vs Egypt",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/Eie98xmcqZoamSjVEyooSpxCQ273fPaSp5P4WKsBJ1H6?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4ooywPrZizKmgeZBTy7fEkJLY9naakvJ4cRmnWrbdHp5Gdcn4yfVvFqgBGEAo52EbB8cSR47EwXY5J7vZ4yg3xDL?cluster=devnet",
    "live": false
  },
  {
    "id": "C2F4axZbTtcX3dsNwubeSksjJranxFLccSamXJW9545B",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/LcnMA7Aq2SS53ItthFFo0IQapjEccBWZLSxY4PbDM8I",
    "match": "Argentina vs Egypt",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/C2F4axZbTtcX3dsNwubeSksjJranxFLccSamXJW9545B?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3pJgXM17UbLMwjCju1gT6tijrRgEQvwcYYgv1spJZNBEE1SsyhKUdDRa1yQA1oKsTM6BpQp5EHQNZz9PPfmpYDVz?cluster=devnet",
    "live": true
  },
  {
    "id": "CUfAT29tnZtHuLPnTQwZEgNg74Zqe5t2vACzXVGnRAzu",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/TGzfq6koUlVMe6JhsgNX3ydUb5UF94tTxm3GNe-ufeA",
    "match": "Argentina vs Egypt",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/CUfAT29tnZtHuLPnTQwZEgNg74Zqe5t2vACzXVGnRAzu?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4daPJTuyPZxiq3FDBQi3fzeMLppwk6QaB1oJWtspN1zhkpx6H2zPLDmjeB9TdG5JYfuXp9EBD6nbrPkhXJ7e1B2T?cluster=devnet",
    "live": true
  },
  {
    "id": "ESycfjfVjYgF95CDnzPNya56zPAuGvuJWtrX2bfziVgW",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/AEU6fhdiQi3uC-z8iwPs_T_aJ1R_LWGqHsjgG2QwqsM",
    "match": "Argentina vs Egypt",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/ESycfjfVjYgF95CDnzPNya56zPAuGvuJWtrX2bfziVgW?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5fLv1Qh6ZEAVSuapHapBst7cydHeXZ3rBxQwrnsXf58TtNxGn4ApLzffUWgL6cFJi14bQ3koXtEqhHe25mdF7F4C?cluster=devnet",
    "live": true
  },
  {
    "id": "5ANpNXFaxVVxeDPqah5to495ZUQVoH3SzCAjd9b35R1u",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/uS_QvctvAWkp5cpksse_D1bvfIVYJhFliHSC6krrLtM",
    "match": "Argentina vs Egypt",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/5ANpNXFaxVVxeDPqah5to495ZUQVoH3SzCAjd9b35R1u?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/uAzyhb1NkLfpNXgyw61vvRp2ih8eun614q2XaZxeKBcWBa71xMZoMKgMpJn9M3fNCSDA9yaEfzmrR1Vn3adrBPS?cluster=devnet",
    "live": true
  },
  {
    "id": "EF5SoomWzbQaKVSEP8P4qmutwXjGyiK8TRJbCHhropZn",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/CwZCquT3GmqYazbJkNBquT_9_S7cC5-ccqOMKj2IjaI",
    "match": "Argentina vs Egypt",
    "score": "2–2",
    "assetExplorer": "https://explorer.solana.com/address/EF5SoomWzbQaKVSEP8P4qmutwXjGyiK8TRJbCHhropZn?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5yDuwg9p2n7ZJs5cyVBHBGarJkbju2PsFj15WAMpBHHtL347BtsJv6wsaQ5UebUbSTobFMqb63sGZj3iMXJXHAdX?cluster=devnet",
    "live": true
  },
  {
    "id": "HLANEfwecX3VTtCaKyosVUXstkxUbMcfApinyYE3P1p4",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/JCiNyDc4PJN3N0fdQ-EVW0tVSLBhZyjOr5nG6LRcBPU",
    "match": "Argentina vs Egypt",
    "score": "3–2",
    "assetExplorer": "https://explorer.solana.com/address/HLANEfwecX3VTtCaKyosVUXstkxUbMcfApinyYE3P1p4?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5S77xNRke5zHqVmV3aCACudEbYWY2EYgApR1wzbRpyyfzLieKgUKAAgZXkXsdj17Km2kUbqa2Ycyma1V72L9eySW?cluster=devnet",
    "live": true
  },
  {
    "id": "BDvQXouZyfqjHwTZTJ7eE4NgPkW3eupNcX5iRqBD5pJS",
    "teams": [
      "Spain",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/8Iws5t-PZKSUljc1JbNooFJHFO1AuUUajwfm-AxDC00",
    "match": "Spain vs Belgium",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/BDvQXouZyfqjHwTZTJ7eE4NgPkW3eupNcX5iRqBD5pJS?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2jWx2J6vBk8ajCGsPVAZsep6NcaELbqoY5oFoG7w2s6HzvECy6PHBoELTrDa1wHybggrq9G4EDGvY8PN8BBhKoTR?cluster=devnet",
    "live": true
  },
  {
    "id": "H4g52jqCUBcKVy1L4ahswLzbzYvASFzPK9eeu5NrvyVF",
    "teams": [
      "Spain",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/G0Nqe6-QQiyw91PX1WytgRYO20kMN9w46r5CWv1cg9Q",
    "match": "Spain vs Belgium",
    "score": "1-1",
    "assetExplorer": "https://explorer.solana.com/address/H4g52jqCUBcKVy1L4ahswLzbzYvASFzPK9eeu5NrvyVF?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/614LK164pALrSi5pGUPxreHcmN2NXqtXWHSkGb9qB8BaimZ8dG9q65hGneGnzfCtFihRcm7XiZFG6LUkjA9KJtkG?cluster=devnet",
    "live": true
  },
  {
    "id": "4Jfxsv3BBSZshzhYRU3FugjRwNdxZRNM7ZCu55Dwi5GL",
    "teams": [
      "Spain",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/dZBKHZ8b8RbX2OK2J69RaYnlOzGxsC0Ttek4oLkryhU",
    "match": "Spain vs Belgium",
    "score": "2-1",
    "assetExplorer": "https://explorer.solana.com/address/4Jfxsv3BBSZshzhYRU3FugjRwNdxZRNM7ZCu55Dwi5GL?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/39YWLFysR9bUzw2D1JY1F7TEHJzC48gGZGfVmk8HT2R2TmLiJ5EvG3vvxXaUYapCw9LTmyLKJG8DeXsvS1ggpJTX?cluster=devnet",
    "live": true
  },
  {
    "id": "5C1wbBV63PiSLXhirQzb3HVHgaGCo75SgVxzRBaCR1vD",
    "teams": [
      "Norway",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/rs_UnyKkHlmK6msdPz--bxl9JQnVVYO3FV5ISq_8g_E",
    "match": "Norway vs England",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/5C1wbBV63PiSLXhirQzb3HVHgaGCo75SgVxzRBaCR1vD?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2c7HZab6bW4rvwLBb1sU6bJwWrjujF1pp16FPaNUJJABm3A3izrA6L6KMQxfY8QvrX828dCEVvzC4c9FAiwQdGBH?cluster=devnet",
    "live": false
  },
  {
    "id": "Dy3BkfQB6zG3YTZZH7QRUWUqtSLoYooSozmADrQoBYp2",
    "teams": [
      "Norway",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/hEnJHlQms2f9qR_ZxIq64_fSOBXxPRRMS5m7wkGLfT4",
    "match": "Norway vs England",
    "score": "1-1",
    "assetExplorer": "https://explorer.solana.com/address/Dy3BkfQB6zG3YTZZH7QRUWUqtSLoYooSozmADrQoBYp2?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2py3qPbzhxguHvGe9atXxhctTxusnT9jgzTzeo28P5QNV6WAkSrbWYJbRf3ywbmJdfds8TfamcL4U1wcyXzvfAsQ?cluster=devnet",
    "live": false
  },
  {
    "id": "DB9XiXYCSTYC1wcWv2c4RA4eYeyGn2sLT71EJdaMs9uh",
    "teams": [
      "Norway",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/FMio15GC-jB6WxmB_O6BXI1QY7ftSfRlouVtBs_Srt8",
    "match": "Norway vs England",
    "score": "2-1",
    "assetExplorer": "https://explorer.solana.com/address/DB9XiXYCSTYC1wcWv2c4RA4eYeyGn2sLT71EJdaMs9uh?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/SFAQsHhkw2d4ukcXpU8iW3S98CqCqewTTLYZPdJ91ZiBfv9Dwx2cJcFeucFASpqDbFg2xk4j1Z9rBWXncoY3SUc?cluster=devnet",
    "live": false
  },
  {
    "id": "9TX8C83duLBu4GwNdRiBDiT2jCDgG3BDM94UXiQ2kzC2",
    "teams": [
      "Norway",
      "England"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/ikhbnda2r8UlB609Qi3fbn5BMrMzkYAgOPyAIAy-8lU",
    "match": "Norway vs England",
    "score": "1-1",
    "assetExplorer": "https://explorer.solana.com/address/9TX8C83duLBu4GwNdRiBDiT2jCDgG3BDM94UXiQ2kzC2?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4KMQsqmv8QEntz9afMPjucmiaoiAnnxZbea6Zpjn7TnZq2yHKBRNYc7uMPLBTtreqXLSEVMRQDnu8yck4oDUQuJQ?cluster=devnet",
    "live": false
  },
  {
    "id": "9si7y8uUE3imdPHzRwEg6VRehZ8yx3B3o5FHJt5j5w2a",
    "teams": [
      "Norway",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/s1WJUtcM9YHwndyg8qNHWUmXrVqmZiQlSOOwgODPqBg",
    "match": "Norway vs England",
    "score": "1-2",
    "assetExplorer": "https://explorer.solana.com/address/9si7y8uUE3imdPHzRwEg6VRehZ8yx3B3o5FHJt5j5w2a?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5gnH16xEcHV6YxnRUpyvXMdadFQZfJ3MQrGcatbGAuVs5Gadw4SrisLSEj1eFeQ5UrgBKWwtyNcByi9E4ouKCqkt?cluster=devnet",
    "live": false
  },
  {
    "id": "9ygq8UjD82jCNhQhRtjoAYxEEQqwWygsu2vvASWiCvMQ",
    "teams": [
      "Argentina",
      "Switzerland"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/TeB2kyod1e-CN8xSmCgc9MBS_I4dCP4RC_EHK4xCSIs",
    "match": "Argentina vs Switzerland",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/9ygq8UjD82jCNhQhRtjoAYxEEQqwWygsu2vvASWiCvMQ?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/ySN4KoKB7ToM8hBPnUVgVQQmt2rXGEYvEzHPBA3HAeug6UsEnJNsD2UpFEbLpcL4b5E3iM1v46NHMpsgcPwDbcH?cluster=devnet",
    "live": false
  },
  {
    "id": "8DXQWKc2eiGmu18LTjaFMXLCUWJn3rGBHbWvZSs2ELa9",
    "teams": [
      "Argentina",
      "Switzerland"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/juZhcJjd6XxbCj3hsuWthyLJkBbzwhHltgNK3rDDa7A",
    "match": "Argentina vs Switzerland",
    "score": "1-1",
    "assetExplorer": "https://explorer.solana.com/address/8DXQWKc2eiGmu18LTjaFMXLCUWJn3rGBHbWvZSs2ELa9?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2G1qjJSim3UStkGAQaVHFvS37H7nA58b6vJkiyG3ZtwW6knDH7pXofdkbEKD65cDYFDVSAuSMvLdrzCPKBQvevH2?cluster=devnet",
    "live": false
  },
  {
    "id": "F7yosTWD1dey25NvaDgoQNcwUgyfwJtYNcP6vsptyHKQ",
    "teams": [
      "Argentina",
      "Switzerland"
    ],
    "label": "RED CARD",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/lLYqXGazXAaKSSDOn3vOZVFMQM7W5VfRXnOkV2SIf1U",
    "match": "Argentina vs Switzerland",
    "score": "1-1",
    "assetExplorer": "https://explorer.solana.com/address/F7yosTWD1dey25NvaDgoQNcwUgyfwJtYNcP6vsptyHKQ?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3kjQLK4rpbx7ckGmgRxBp86jVWk9HUaxrbRi8SvaZ3PRt5vGaqGkEnAffvWoF5QByUWYgAiDh1YvUKnN45T1KYYU?cluster=devnet",
    "live": false
  },
  {
    "id": "5doMRvdmXHGSser6QMhSyJpoqViqN4FBwCDVowBbK2uk",
    "teams": [
      "Argentina",
      "Switzerland"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/16fJD10fCZ9DWdxQcbyZFAWL4ZR75iyI97C5MNGXlNc",
    "match": "Argentina vs Switzerland",
    "score": "2-1",
    "assetExplorer": "https://explorer.solana.com/address/5doMRvdmXHGSser6QMhSyJpoqViqN4FBwCDVowBbK2uk?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/B7KXWb95XUv7aBHew7GU5okoEauzCMEebzjaR1P3MFiPkdRttwu81Vpj36EEq1P1Jzj1oQFyneEqFG4bivB2T1r?cluster=devnet",
    "live": false
  },
  {
    "id": "2qdjU9vDv8JBenHSyS9omAKciqpdpqyAqng7Q4uMcZFZ",
    "teams": [
      "Argentina",
      "Switzerland"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/Q2W72Vnrz7tbz-xLteqig_h4holF3jtWgCKHVVkDs6M",
    "match": "Argentina vs Switzerland",
    "score": "3-1",
    "assetExplorer": "https://explorer.solana.com/address/2qdjU9vDv8JBenHSyS9omAKciqpdpqyAqng7Q4uMcZFZ?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/Rjxxvu7CxaW2fVadRi5RNBwV8uKBJDpAUVFnEdMUd7FetPDbrL3SvBTYupsUnLpSbXc6TYGgdMA3ZogCFdx8UYr?cluster=devnet",
    "live": false
  },
  {
    "id": "5pVSHrZ9GcoTWZdpi2paJpkBSL2qHAXQatXhvLAMMhj2",
    "teams": [
      "France",
      "Spain"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/N5fDqFeFOJyAHC366wqaETl73UsY561Dl5SeHTTOkLE",
    "match": "France vs Spain",
    "score": "0-1",
    "assetExplorer": "https://explorer.solana.com/address/5pVSHrZ9GcoTWZdpi2paJpkBSL2qHAXQatXhvLAMMhj2?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5SpBrYt73DUfkrMWUmKx3fkzVcGH6XuT345o2t3RTKENjxu1g2tyQwaqbemscrftns19kiptMPeBUueQKDHpVnwk?cluster=devnet",
    "live": true
  },
  {
    "id": "8rteWHaVH1bCiR51RbS8TAwN4mh6BXhyigPpSGvevnpi",
    "teams": [
      "France",
      "Spain"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/0hbZ7eowbMh_nTsdDQA49lFcNG_v-IYQea-f99g1w3U",
    "match": "France vs Spain",
    "score": "0-2",
    "assetExplorer": "https://explorer.solana.com/address/8rteWHaVH1bCiR51RbS8TAwN4mh6BXhyigPpSGvevnpi?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/25GkSpdG4zciFc9z4cLUtWmowh9fYrH6YgzTb5GF8eDxZarXbLeDofvQPTK58MuHffE2HFiuAURhAj8zXefFZsKD?cluster=devnet",
    "live": true
  },
  {
    "id": "4eJmkMbHz2YarXNYARczzS3dW21B3zHvaoaHvK2KNB8T",
    "teams": [
      "France",
      "Spain"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/rmglAUFWvCeIaZ6qw1iswq06k2is4emh3nzimbsmGBQ",
    "match": "France vs Spain",
    "score": "0-3",
    "assetExplorer": "https://explorer.solana.com/address/4eJmkMbHz2YarXNYARczzS3dW21B3zHvaoaHvK2KNB8T?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/34ZXkqc9F44UfeLqqzWhCfshJugDCJsuWTU6SMVduKBh5LBvMdNo3XmvTchrfBZSswCPRXwJyH7XkkpzgyjQVxr?cluster=devnet",
    "live": true
  },
  {
    "id": "CoQmWrx6ikrH5veRZu4jzTsRpHSV6VzjMYL4jdt22Jk6",
    "teams": [
      "France",
      "Spain"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/4T5zxDdZhlCzQutHP1tgPCrBwo8KndgiFx4zsc7sDzs",
    "match": "France vs Spain",
    "score": "0-2",
    "assetExplorer": "https://explorer.solana.com/address/CoQmWrx6ikrH5veRZu4jzTsRpHSV6VzjMYL4jdt22Jk6?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4EVqXiQztFnDjDPTLyFtfeHRjazNYts9ZYGzHz1cQ8enisUpxPZsdhAVfRsdN2dFfGPe7jaJ2Z6dAaDFvGo1hdWh?cluster=devnet",
    "live": true
  },
  {
    "id": "B1unSjuf9Hx1RPBY3fto99eB5CPLDRqhvU6YH69pR2ck",
    "teams": [
      "England",
      "Argentina"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/3nXlq6vsgxaYMdBLOENhBy2WKQBwrchpLyjs2Bffcjw",
    "match": "England vs Argentina",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/B1unSjuf9Hx1RPBY3fto99eB5CPLDRqhvU6YH69pR2ck?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/YZiqMMHP5PBcKJ6dNFkKqaJjofk6oGwCTAt5tUX8DioCqzU1bhyUn29GZnFTRvGuuCM3iYSKMjNQwuV5LqLkX1e?cluster=devnet",
    "live": true
  },
  {
    "id": "FxMk1sgcNJGdCnTZCyL4mUMryfo4EeiaCeWbNvhVMcTH",
    "teams": [
      "England",
      "Argentina"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/ylaBsykObXV2IZuahFG68E4Z5EAUanWwSDHZLJMbhZo",
    "match": "England vs Argentina",
    "score": "1-1",
    "assetExplorer": "https://explorer.solana.com/address/FxMk1sgcNJGdCnTZCyL4mUMryfo4EeiaCeWbNvhVMcTH?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5MvJYYksXeVmzgqq2YkUF8m94ixP65RTK4v1QF2zEYPB4rDr2qq2rMGu7zkPhtej6ev7LW26JHpnUHHXBc6Ba2rY?cluster=devnet",
    "live": true
  },
  {
    "id": "4yTbVRJAMrcoP1VvgA9r1gZ7FkKD2wXdiGvU8dAcshwz",
    "teams": [
      "England",
      "Argentina"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/MIuD3nY2KXY9WCQg0X4z6pz0jnZcLtdngkHTRQq9ptg",
    "match": "England vs Argentina",
    "score": "1-2",
    "assetExplorer": "https://explorer.solana.com/address/4yTbVRJAMrcoP1VvgA9r1gZ7FkKD2wXdiGvU8dAcshwz?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3d34H1mDjFnaow5tsFouspGxsmei95VJFs8XvBjaXPjisRPA3DDWyewMF13DJS4XHgfGr9e9Vq8CFGU3Uazj8qrS?cluster=devnet",
    "live": true
  },
  {
    "id": "Expdikdjf1wJb2ksqy3sEt1ZiHRiyZzLW1w2TyZD8oBg",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/gOW75JyJETykn4rLYcgVD-VrqbPbWFwyB8Z1cnfI960",
    "match": "France vs England",
    "score": "0-1",
    "assetExplorer": "https://explorer.solana.com/address/Expdikdjf1wJb2ksqy3sEt1ZiHRiyZzLW1w2TyZD8oBg?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/sQCjCPpoEJNQL9YuMtG8fJom4uZTwZqckxJmedGQzKqAAwj9iuyebTaVpUWhz6R4GcKQiUtWy2Ci9isee6robPb?cluster=devnet",
    "live": true
  },
  {
    "id": "Mr3ETk9U7ZEf9wsrAbaFSQnPhmGxCMnabFffHvi2TdP",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/g4gKieHu7GuJ3Iv1weqpnJce7KIqf9ukue531OasHA0",
    "match": "France vs England",
    "score": "0-2",
    "assetExplorer": "https://explorer.solana.com/address/Mr3ETk9U7ZEf9wsrAbaFSQnPhmGxCMnabFffHvi2TdP?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/CgChk9Rd6RXuejNTsVPWm7EBdawQbdQymJohtTC1uWA79Q4yusVAWNSjSHXx2ssb4vNQbtGqHiRmJsE3ZWFKHTR?cluster=devnet",
    "live": true
  },
  {
    "id": "DNLwBN8CL5TR1duJueqKKVWPEPnTQB4NBxYQ4D7KirZ5",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/SuDWClzRBZ5EskwPi98mkKVJ3ZfTZlbIAPw9eNweLbo",
    "match": "France vs England",
    "score": "0-3",
    "assetExplorer": "https://explorer.solana.com/address/DNLwBN8CL5TR1duJueqKKVWPEPnTQB4NBxYQ4D7KirZ5?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5jtqrPJ9vJqDMfQMdQaEMP5WYe29Ki8p6XeT3SLesiV4R51fCeHcWhZtGZyXKPNwnNwJ6PrxG6x5aYy4SqP9bHyA?cluster=devnet",
    "live": true
  },
  {
    "id": "FwMERbng1t1Dm7N63mzLQDXRMTPTQ38V9GUi9tpe26KA",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/brLJeje7p3cIz2fMc1YFqpGA2kPx5zSFrPkdjsOts_I",
    "match": "France vs England",
    "score": "0-4",
    "assetExplorer": "https://explorer.solana.com/address/FwMERbng1t1Dm7N63mzLQDXRMTPTQ38V9GUi9tpe26KA?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2EniLm4i8CwnSgyexRG31LE3t4WXA8WC1FrSzk9mDija35QsicLYsbFqMv3NnvvjrscxfytCc1VoupHxHre3fwEA?cluster=devnet",
    "live": true
  },
  {
    "id": "AEYLrPEFr9mQtyoMhhfxgXHHZJmDmvjhqq5hT7muPGw4",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/pQWnudtYe7RsaQsbOFH8lFWn19CloGgc4GB01O3LNvg",
    "match": "France vs England",
    "score": "1-4",
    "assetExplorer": "https://explorer.solana.com/address/AEYLrPEFr9mQtyoMhhfxgXHHZJmDmvjhqq5hT7muPGw4?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/H6Kjfe8NfeYngY9gwM9xGsQdEXcQ8BBxjgcg9xWPaBYFjQ1UioeSSc23HnDFHQbycqcgvhWBWXmBqvXTAWRSyQm?cluster=devnet",
    "live": true
  },
  {
    "id": "GfAE2WdhQs1GBhHrVAamQua6qXE8Kkwd8ttu8hjjVhau",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/4Z2LIX_8doy-HYiG1nq7B8e7dyFqaZl3EZzn9MTX2A0",
    "match": "France vs England",
    "score": "2-4",
    "assetExplorer": "https://explorer.solana.com/address/GfAE2WdhQs1GBhHrVAamQua6qXE8Kkwd8ttu8hjjVhau?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2jHPGCCsn7v6WKkFWWYM2mS5KofT7Pb3chMMxPvw7qh4U8J8xb3saXqoDms2jUJSPeJfsBdZsHdFBnwNEgQaoxnw?cluster=devnet",
    "live": true
  },
  {
    "id": "4LtcSF7fYLo2t6ad8jJYwW2EymDahyfpHD47PZvBSmB4",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/7upOxxIsmttX8vY7wtkRACH_Glai4Me-MdzrCv-zKEI",
    "match": "France vs England",
    "score": "3-4",
    "assetExplorer": "https://explorer.solana.com/address/4LtcSF7fYLo2t6ad8jJYwW2EymDahyfpHD47PZvBSmB4?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/63vspB3QDPD5Z3mdGRqdEAKPuqmyXVieZYVV3ZNUN5968pwkfi8hW1HcJEWjW7kuttK6NH7DNSEwvAbVALmmjfRp?cluster=devnet",
    "live": true
  },
  {
    "id": "8kKmCoNqzHjDjiZ23fz1zTHkXw7Agi4wN4QrU6JZshc6",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/lvDGp8HYd9MWavNb6Aq47uHJ7ih4q4vI7IwLai4wQoQ",
    "match": "France vs England",
    "score": "3-5",
    "assetExplorer": "https://explorer.solana.com/address/8kKmCoNqzHjDjiZ23fz1zTHkXw7Agi4wN4QrU6JZshc6?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4NaNZgN1hBGMJEx7tyPzBc2MaNRHJQaHu8HJ7n8nUMDC1GDW5DgbruV6AppsimfbVhKLECVshB2jixGBwvxWNgyX?cluster=devnet",
    "live": true
  },
  {
    "id": "Dh26g9yRzWVSov4f5vC7JCDSg73CGZXr3heW68HHg99z",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/GvhlpgmYOl2HRmiWclt789kIC2U8V_BH3V9YGFMve_U",
    "match": "France vs England",
    "score": "4-5",
    "assetExplorer": "https://explorer.solana.com/address/Dh26g9yRzWVSov4f5vC7JCDSg73CGZXr3heW68HHg99z?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4YyUwnFK3ujT4v2K1GgG1eK1mteBMfUwHCK3RGwL2JrnoBMjZeGREpTK1ko5GH3Eqru4gHNbSEz7Lxf4qnmrfqRU?cluster=devnet",
    "live": true
  },
  {
    "id": "BGVKQ6VUJxsdcA1egESU1VNiyMgSA8gQzC53dhuK73Zm",
    "teams": [
      "France",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/gBGAUOORUCYSW_Zong7tn-JdVQ3CdFq1WcDzKzCMoMg",
    "match": "France vs England",
    "score": "4-6",
    "assetExplorer": "https://explorer.solana.com/address/BGVKQ6VUJxsdcA1egESU1VNiyMgSA8gQzC53dhuK73Zm?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/54TcZGViHiYPdbbby4bXaq1M4vAuHY6gCQDh7UhtUPE4WxFQvxtqapUvWhvk3e8TfKUVB1GCWr64yP6MuRpaBXbU?cluster=devnet",
    "live": true
  },
  {
    "id": "DCrqTqCUey9ZwtDRAxyb4qaY37nrheNimELovSKELGUC",
    "teams": [
      "Spain",
      "Argentina"
    ],
    "label": "RED CARD",
    "tier": "legendary",
    "supply": 10,
    "image": "https://arweave.net/y4PP50_cgz-uKJAPum06WrKkFwVsSVnuvWDXuLkwAEI",
    "match": "Spain vs Argentina",
    "score": "",
    "assetExplorer": "https://explorer.solana.com/address/DCrqTqCUey9ZwtDRAxyb4qaY37nrheNimELovSKELGUC?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4XTiJYFEXDhboF6ZPVA3yuzSRiVeUZT6eD6XPvxPGNxRxV28mKvhApT1nvXjcX2uToHNAkL3KiGTbbAQGuYKn24v?cluster=devnet",
    "live": true
  },
  {
    "id": "6oz9ciPGLuAJqsfXA7PRqex5Dvhg6pJpH9zJTf9jsckf",
    "teams": [
      "Spain",
      "Argentina"
    ],
    "label": "GOAL",
    "tier": "legendary",
    "supply": 10,
    "image": "https://arweave.net/HZwFG_ANoQ4v5A31ITUmdRvWy9aBliUmUXduHZxiB0E",
    "match": "Spain vs Argentina",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/6oz9ciPGLuAJqsfXA7PRqex5Dvhg6pJpH9zJTf9jsckf?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/26JByhrVorVj2kmLd56QBKcapTsmnt529eYA2TePTTyEW4CMu3jSU2zNLkvCFW893FVkQRLqL7KXC3Nt52RzCDXB?cluster=devnet",
    "live": true
  },
  {
    "id": "9F9WXrwdkQccbCXugtcB27tuTT2Ck9neYyNXWZzANgs",
    "teams": [
      "Spain",
      "Argentina"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "legendary",
    "supply": 10,
    "image": "https://arweave.net/5X6lGqWZjgsbsZubWfnyeG7Ep2GOE03b43LIqN03dYg",
    "match": "Spain vs Argentina",
    "score": "0-0",
    "assetExplorer": "https://explorer.solana.com/address/9F9WXrwdkQccbCXugtcB27tuTT2Ck9neYyNXWZzANgs?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4Mfj6LPmnLcq3fDQn1osAKbmsd6o1jCNDFVZVLdaC5PTR5keX43MDNDQhoTRZvR663xDfugRqJ18AW91RciuYX2e?cluster=devnet",
    "live": true
  },
  {
    "id": "3yJbfhfHMXoc5y2WELqvovk65Vft2GhVm5BiRfKZxwEJ",
    "teams": [
      "Spain",
      "Argentina"
    ],
    "label": "GOAL",
    "tier": "legendary",
    "supply": 10,
    "image": "https://arweave.net/tcrZ3oW_8yqyLjK5bIl-dJA7hgAdWKMW9ryuOed16v0",
    "match": "Spain vs Argentina",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/3yJbfhfHMXoc5y2WELqvovk65Vft2GhVm5BiRfKZxwEJ?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/z8DqL4J8osZgvNtCt35De8P8FVM4VyMgVYyULNptjhcjUw6TjTKmYnPXDFXbGHddmeQBpE5un3coYBq9vma9ivw?cluster=devnet",
    "live": true
  },
  {
    "id": "HKCwFN9U5QgZ4t6hwhdAy3efYYdn2VcGavYzBA1P9k3R",
    "teams": [
      "Spain",
      "Argentina"
    ],
    "label": "GOAL",
    "tier": "legendary",
    "supply": 10,
    "image": "https://arweave.net/Zn-mLViwRqxx0_ofRhQ-UG3pce6T_Rufs5vxkUe6bJE",
    "match": "Spain vs Argentina",
    "score": "2-0",
    "assetExplorer": "https://explorer.solana.com/address/HKCwFN9U5QgZ4t6hwhdAy3efYYdn2VcGavYzBA1P9k3R?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4VQKCTxB64EXeAxSUXAM4sdgLfDSXYqHTuvHpESJebf1mrCwCrvcMhboeJUXSdirH2RGYH5SH6Rn7Sgx8vi5rqcB?cluster=devnet",
    "live": true
  },
  {
    "id": "C2Y6cMzZ99in45YEmNTfYZBRHVDdBneGa8w8CyRGk3Gx",
    "teams": [
      "Spain",
      "Argentina"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "legendary",
    "supply": 10,
    "image": "https://arweave.net/JxttPAxvY2NOB-qR7HaYtDC_ngMJaIAAHqL015Y-NpA",
    "match": "Spain vs Argentina",
    "score": "1-0",
    "assetExplorer": "https://explorer.solana.com/address/C2Y6cMzZ99in45YEmNTfYZBRHVDdBneGa8w8CyRGk3Gx?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3HaTiXv6CnKVWbkkwJzCHtneGAsa2AV5Um4TNyVbqrfvkKwkBWXvxhu2TPLTGv8UeqxiGsbBUx22S6TVkibx3X1F?cluster=devnet",
    "live": true
  }
];
