// AUTO-GENERATED by gen-pool.mjs — do not edit by hand.
export default [
  {
    "id": "4fuar55aCMZgvxMZM1sboXcCwr6jLMuANwNtC69sbCzx",
    "teams": [
      "Argentina",
      "Cape Verde"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/8GeUKV4tWmw4vboYAZOTAArTLVMEh022Kt3eW34qT5M",
    "match": "Argentina vs Cape Verde",
    "score": "1–0",
    "assetExplorer": "https://explorer.solana.com/address/4fuar55aCMZgvxMZM1sboXcCwr6jLMuANwNtC69sbCzx?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3jdjouck3uf3rnE1ktcYa4BwminXVF62in959xqcxpfKyNYMDuamhdGpTPpb5bz79zfmSvZRw3pQTfJAwnKwXPBZ?cluster=devnet",
    "live": false
  },
  {
    "id": "qdmsBUhmf6yL8PEfmsmEAVHCU5mw9RETAd4Wvp8oWtW",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/wFVRA7XHIZC2-3k3JT4qY798qxTIdB3qglrBGvIJt9w",
    "match": "Brazil vs Norway",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/qdmsBUhmf6yL8PEfmsmEAVHCU5mw9RETAd4Wvp8oWtW?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/XtjcnYiFf2qyP9E7UEL527icpa3L2QRJm2cFsVrqKDBA15nn3fTjaAKL1QpQZVx2q58YxUxPEbWWrL7muCSzGW2?cluster=devnet",
    "live": false
  },
  {
    "id": "8rqd4KjugeQsjzakEM7wTSLT2Vuip7rjAoYxkGuVtPKZ",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/undefined",
    "match": "Brazil vs Norway",
    "score": "0–0",
    "assetExplorer": "https://explorer.solana.com/address/8rqd4KjugeQsjzakEM7wTSLT2Vuip7rjAoYxkGuVtPKZ?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2khGhrT9FdvTe9DN3FERRL4EJEhT84L8A5bHTqE47y5gEnFPEnBR3UVEac4WMU4AhB1QfVgcophswJonw8yhkFh7?cluster=devnet",
    "live": false
  },
  {
    "id": "2rHiPEuVqTyKz4nRtEWBznQum7mthQCXAxsAtKax87MF",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/bxp2R1qI4UD3AienbgJ3WnpA6iacoentHTK4i3kEk1A",
    "match": "Brazil vs Norway",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/2rHiPEuVqTyKz4nRtEWBznQum7mthQCXAxsAtKax87MF?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2K68D78EAYg8WAbbDatFYTHXiaEfUR58HAZTrTy11tqmA31mNKkD2SzVAMBFHRQkwwbQGsMNcSuf9HK2TcpiN7Q7?cluster=devnet",
    "live": false
  },
  {
    "id": "ExXsQfwSio7v9mn2Bw9BfftBVWFLBMNkduicbGvDvsBW",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/iLMwaVMucrogZ_empCuS54GxBDW_Y_ljmv87OpUTFmY",
    "match": "Brazil vs Norway",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/ExXsQfwSio7v9mn2Bw9BfftBVWFLBMNkduicbGvDvsBW?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2F1goozAE4NW7eUM1EcJAQFn9Z25CLj1MxRXcxJ1UfjNqG97gmywNcQ2VaWz3eb4tjcKyFHrYYgWq3atWqYy2dLV?cluster=devnet",
    "live": false
  },
  {
    "id": "CDtHAELeWAwrs5qukZWjt3umDuJ9zEqXF6oQuDtGCRD8",
    "teams": [
      "Brazil",
      "Norway"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/Icx0W2rRnIPW25gTCTB1FOrR07URKJOCWPn1Yn_GxNo",
    "match": "Brazil vs Norway",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/CDtHAELeWAwrs5qukZWjt3umDuJ9zEqXF6oQuDtGCRD8?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/auvpfUwtQ9e1HGoi8EPqGMAXq9E6WFnR5LZnN1mi7uAz6wvyyRuyMQZVy1zwPKMr5nTj4KjZqvXpNjKKdA5tMBc?cluster=devnet",
    "live": false
  },
  {
    "id": "HUVVDAo7ziBMzfJGooMdb8wkk2ZwTE4WbKSwqqYHPzP7",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/iM9sq2iaj3-Xk_Q6hx44WVhZSUg416MSSMU352W93-k",
    "match": "Mexico vs England",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/HUVVDAo7ziBMzfJGooMdb8wkk2ZwTE4WbKSwqqYHPzP7?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/ukWpqyJT1PEw6SCb2qrp2ey9vJbWL5Qyu3P23A8V5MmQdYAcNWtmTptMnitPVvGrKbpK15fVRVQvv3e3wMNoi8g?cluster=devnet",
    "live": false
  },
  {
    "id": "B3dVq2ZtXfhk2phPFvoYQwbTGDUTFuwFCeZWMNfeqWwu",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/lYlgD8pRMoMv2FfAy8m53la4pQjFfxp2bbcM7P_KMG4",
    "match": "Mexico vs England",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/B3dVq2ZtXfhk2phPFvoYQwbTGDUTFuwFCeZWMNfeqWwu?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/2MPMVwR8UYNq5xjy12WXCwjtFMoZZ71o1EhMXuwfVdK1TGWYkLzKdcZ8nqwuQDCf6Cu9nviaWjssRQvBwqMmZnoC?cluster=devnet",
    "live": false
  },
  {
    "id": "huz4VgEb7cEqwJ8bf9E2er4eZ78BLP2r2MUXmfKfwzL",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/byVgL1R9etde0lp0d1G7XRv8D6ZCiu_KFK1FUbsEOZo",
    "match": "Mexico vs England",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/huz4VgEb7cEqwJ8bf9E2er4eZ78BLP2r2MUXmfKfwzL?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/Z2dKF2jhACpBaK8MCmPgzBh2FRLGW1D5yLUFmveAM4cRJxdYkNmPJ2EFkPAS85GnYMv3HGGzbQQFj5gmKEvq1on?cluster=devnet",
    "live": false
  },
  {
    "id": "BzNyknVxYGR68yxvXQTTRvw4twzyqM498AedhwwMN5CN",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "RED CARD",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/KJBgRRNXndIWqCDpEM0J-ria4n-P5w4yxZ6TFtBBWEM",
    "match": "Mexico vs England",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/BzNyknVxYGR68yxvXQTTRvw4twzyqM498AedhwwMN5CN?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/dLb9TDFcGwpzervm4BhnQmJ1Ru8y97Z9fiJpSMrJNB6qkFLR6vaWrywzprfa9GxYe6rdazF6e8mszVijtB21Ecq?cluster=devnet",
    "live": false
  },
  {
    "id": "75vXJPgsRfTip6CiDRWBgL2iKtL2VXQ5NnZKrVvgYVxY",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/Q_PweMCu3sCkY6lUB-o-fql1kfScZTHAzwX6Zp4ZIkM",
    "match": "Mexico vs England",
    "score": "1–3",
    "assetExplorer": "https://explorer.solana.com/address/75vXJPgsRfTip6CiDRWBgL2iKtL2VXQ5NnZKrVvgYVxY?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5oWvt4zarYnaihRdwBfdPF93evJKQu2hA7tMQ73ugsize2tUs8juju5k6a4iqAVu1cWVC9jWr72AE5T8dMrpdsyT?cluster=devnet",
    "live": false
  },
  {
    "id": "F6LFJ2kESD2rQGRipe3vQVwsmC6SvEUDyuFjjkYQ1jXB",
    "teams": [
      "Mexico",
      "England"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/HX7yeikLrn3l-FAPz84RUuts1AMPxIFi8QRHocd1MAw",
    "match": "Mexico vs England",
    "score": "2–3",
    "assetExplorer": "https://explorer.solana.com/address/F6LFJ2kESD2rQGRipe3vQVwsmC6SvEUDyuFjjkYQ1jXB?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5pRaGgSKvc4MiSpJ7rn1jT6QoMXCHv9pY14q1NQ8X9CdrFoNEK3t8SykW5mVeFRrQxBh4vrUWqc58xwKpeeqFJVw?cluster=devnet",
    "live": false
  },
  {
    "id": "Cv2bqwj15wRZsVb9yoyjRkK8TXcStoWMzmxF8Au8fEyS",
    "teams": [
      "Portugal",
      "Spain"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/wMV2qvh8N0-wmnd1RHHUSWnOb_yuYvEmSUdMm9hj2iw",
    "match": "Portugal vs Spain",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/Cv2bqwj15wRZsVb9yoyjRkK8TXcStoWMzmxF8Au8fEyS?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5wEZzKtnoEcXhxNUxLvJvLpLkV7vEhWzwGuyrSTAo4jaNs2WFh8CTdy7LkRMd3nCcZJv7ZSgsSsjMMacz4HAW6Xw?cluster=devnet",
    "live": true
  },
  {
    "id": "FXBsRTFgYa57wDcdoGjmQisABm3YFEsez55KqE2kERFN",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/undefined",
    "match": "USA vs Belgium",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/FXBsRTFgYa57wDcdoGjmQisABm3YFEsez55KqE2kERFN?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/kLnvYDy9qBRJaVaJZFyFzqvvJ9Czj86rthRf8rgHNPiKqKVLs2pdk9UbfHWj24qDPFXv7RpAT9Yg9kg3A2JCceL?cluster=devnet",
    "live": true
  },
  {
    "id": "DexpoT2emg9sMPErKmEYz8UDHmvH4BzCnqwTgBuqEsLB",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/gJp4sQWIujq6FhjZ2enCt78lXOgOqSz8KCKQzDSDu-M",
    "match": "USA vs Belgium",
    "score": "1–1",
    "assetExplorer": "https://explorer.solana.com/address/DexpoT2emg9sMPErKmEYz8UDHmvH4BzCnqwTgBuqEsLB?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/31tL87UYcovjQ1e7nqcRt3ByTQZmHk6PCG6G4u69PNGpsifCGY6hFuSjNf3BAyhzNVfbK6vsbHTQSQcYQZeKk22q?cluster=devnet",
    "live": true
  },
  {
    "id": "9BnSVxPE8wdYhAzhkj2prz7rgtZHbUiv7G4p6tATwsTo",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/xPjHC3BOPzt_jYW0PPjVSc-dqLs-1AWYDX7AydOJ7V8",
    "match": "USA vs Belgium",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/9BnSVxPE8wdYhAzhkj2prz7rgtZHbUiv7G4p6tATwsTo?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3pyjN98ax34zRJAUmZ2NzqV6bRHminARPZB9Mmf3BktrKVhpgPv5SF4uNaQ33YmFnaBYj2Zmy6o4QbKKtuqnDHt4?cluster=devnet",
    "live": true
  },
  {
    "id": "Gwn1UL8LuaxxqLYFd3PUVpx2e7gwmxVNxYwxkWeAjLPo",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/5AbmyLytS1J_VEsSDxNiwlFLSB3jOMdj8kdKZuIoMDg",
    "match": "USA vs Belgium",
    "score": "1–3",
    "assetExplorer": "https://explorer.solana.com/address/Gwn1UL8LuaxxqLYFd3PUVpx2e7gwmxVNxYwxkWeAjLPo?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/43TqCueDzkTBiFgETMvtoagHhpUqq2N3ekR2WQwrcy5i6UyMBL69TZ3tC893dr6RomStrsua612YtY9xu1rtXMMm?cluster=devnet",
    "live": true
  },
  {
    "id": "5AxNeSbTrGGdr6wtStsH9bpp2H6d1hVPePhWWcUVSg7y",
    "teams": [
      "USA",
      "Belgium"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/8511RRg9beg9lXjwk_3apAMSroyO9MXKRbKJd3Yguk0",
    "match": "USA vs Belgium",
    "score": "1–4",
    "assetExplorer": "https://explorer.solana.com/address/5AxNeSbTrGGdr6wtStsH9bpp2H6d1hVPePhWWcUVSg7y?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4EkeD3nLj8oXkaUtQcuA2Hhud2eaCbnYuqGh8TwqKCWhc1hb4fzxvY7zX9TCkDZrxjJiDYSAbs67h9HhdPJp9mxS?cluster=devnet",
    "live": true
  },
  {
    "id": "Eie98xmcqZoamSjVEyooSpxCQ273fPaSp5P4WKsBJ1H6",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/M7FCSVGwvyflF_Qk9JlXRBPpKUOUrqMoSDS3rB7nEow",
    "match": "Argentina vs Egypt",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/Eie98xmcqZoamSjVEyooSpxCQ273fPaSp5P4WKsBJ1H6?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4ooywPrZizKmgeZBTy7fEkJLY9naakvJ4cRmnWrbdHp5Gdcn4yfVvFqgBGEAo52EbB8cSR47EwXY5J7vZ4yg3xDL?cluster=devnet",
    "live": false
  },
  {
    "id": "C2F4axZbTtcX3dsNwubeSksjJranxFLccSamXJW9545B",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/C9AQAdqU5G-fmzlCnQm-lDy7kaRI4UFR3_vU7MGGquo",
    "match": "Argentina vs Egypt",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/C2F4axZbTtcX3dsNwubeSksjJranxFLccSamXJW9545B?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/3pJgXM17UbLMwjCju1gT6tijrRgEQvwcYYgv1spJZNBEE1SsyhKUdDRa1yQA1oKsTM6BpQp5EHQNZz9PPfmpYDVz?cluster=devnet",
    "live": true
  },
  {
    "id": "CUfAT29tnZtHuLPnTQwZEgNg74Zqe5t2vACzXVGnRAzu",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "VAR · GOAL DISALLOWED",
    "tier": "drama",
    "supply": 100,
    "image": "https://arweave.net/undefined",
    "match": "Argentina vs Egypt",
    "score": "0–1",
    "assetExplorer": "https://explorer.solana.com/address/CUfAT29tnZtHuLPnTQwZEgNg74Zqe5t2vACzXVGnRAzu?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/4daPJTuyPZxiq3FDBQi3fzeMLppwk6QaB1oJWtspN1zhkpx6H2zPLDmjeB9TdG5JYfuXp9EBD6nbrPkhXJ7e1B2T?cluster=devnet",
    "live": true
  },
  {
    "id": "ESycfjfVjYgF95CDnzPNya56zPAuGvuJWtrX2bfziVgW",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/QgO1aZKpjJFqwWZ-NVhmJxfTfcuxXaeXsijuh_qVLFM",
    "match": "Argentina vs Egypt",
    "score": "0–2",
    "assetExplorer": "https://explorer.solana.com/address/ESycfjfVjYgF95CDnzPNya56zPAuGvuJWtrX2bfziVgW?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5fLv1Qh6ZEAVSuapHapBst7cydHeXZ3rBxQwrnsXf58TtNxGn4ApLzffUWgL6cFJi14bQ3koXtEqhHe25mdF7F4C?cluster=devnet",
    "live": true
  },
  {
    "id": "5ANpNXFaxVVxeDPqah5to495ZUQVoH3SzCAjd9b35R1u",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/0jtkSykIlc_zUDr59QKKT2AzFr38txUGnaIMLV1G9ds",
    "match": "Argentina vs Egypt",
    "score": "1–2",
    "assetExplorer": "https://explorer.solana.com/address/5ANpNXFaxVVxeDPqah5to495ZUQVoH3SzCAjd9b35R1u?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/uAzyhb1NkLfpNXgyw61vvRp2ih8eun614q2XaZxeKBcWBa71xMZoMKgMpJn9M3fNCSDA9yaEfzmrR1Vn3adrBPS?cluster=devnet",
    "live": true
  },
  {
    "id": "EF5SoomWzbQaKVSEP8P4qmutwXjGyiK8TRJbCHhropZn",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/gK3CWMcLkeGAhDXXuTS6cm7LBz-BHHhLuKCFmKa-QZQ",
    "match": "Argentina vs Egypt",
    "score": "2–2",
    "assetExplorer": "https://explorer.solana.com/address/EF5SoomWzbQaKVSEP8P4qmutwXjGyiK8TRJbCHhropZn?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5yDuwg9p2n7ZJs5cyVBHBGarJkbju2PsFj15WAMpBHHtL347BtsJv6wsaQ5UebUbSTobFMqb63sGZj3iMXJXHAdX?cluster=devnet",
    "live": true
  },
  {
    "id": "HLANEfwecX3VTtCaKyosVUXstkxUbMcfApinyYE3P1p4",
    "teams": [
      "Argentina",
      "Egypt"
    ],
    "label": "GOAL",
    "tier": "base",
    "supply": 1000,
    "image": "https://arweave.net/3oqRi5HJ4TuHEQD_rUiduc6mZ_caYTjwRDEnPyhUpHs",
    "match": "Argentina vs Egypt",
    "score": "3–2",
    "assetExplorer": "https://explorer.solana.com/address/HLANEfwecX3VTtCaKyosVUXstkxUbMcfApinyYE3P1p4?cluster=devnet",
    "proofExplorer": "https://explorer.solana.com/tx/5S77xNRke5zHqVmV3aCACudEbYWY2EYgApR1wzbRpyyfzLieKgUKAAgZXkXsdj17Km2kUbqa2Ycyma1V72L9eySW?cluster=devnet",
    "live": true
  }
];
