#!/usr/bin/env node
// Генерирует src/pool.js из gallery/moments.json — серверный (доверенный) пул моментов,
// из которого воркер выбирает карточку для команды фаната и чеканит edition.
// Запуск: node gen-pool.mjs   (после каждого ребилда галереи, чтобы арт-URL были свежими)

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));
const moments = JSON.parse(readFileSync(join(DIR, '..', 'gallery', 'moments.json'), 'utf8'));

const EVENTS = {
  GOAL: { label: 'GOAL', tier: 'base' },
  GOAL_REVOKED: { label: 'VAR · GOAL DISALLOWED', tier: 'drama' },
  RED_CARD: { label: 'RED CARD', tier: 'drama' },
  YELLOW_CARD: { label: 'YELLOW CARD', tier: 'base' },
};
const supplyByTier = { legendary: 10, drama: 100, base: 1000 };

const pool = moments.map(m => {
  const ev = EVENTS[m.type] ?? { label: m.type, tier: 'base' };
  const tkey = m.legendary ? 'legendary' : ev.tier;
  const [a, b] = String(m.match || ' vs ').split(' vs ');
  return {
    id: m.asset,
    teams: [a, b].filter(Boolean),
    label: ev.label,
    tier: tkey,
    supply: supplyByTier[tkey] ?? 500,
    image: m.image,                 // arweave.net (постоянный) после миграции
    match: m.match,
    score: m.score,
    assetExplorer: m.assetExplorer,
    proofExplorer: m.proofExplorer,
    live: !!m.live,
  };
});

writeFileSync(join(DIR, 'src', 'pool.js'), `// AUTO-GENERATED by gen-pool.mjs — do not edit by hand.\nexport default ${JSON.stringify(pool, null, 2)};\n`);
console.log(`pool.js: ${pool.length} moments, teams: ${[...new Set(pool.flatMap(p => p.teams))].sort().join(', ')}`);
